apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: test-node
  name: test-node
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      run: test-node
  template:
    metadata:
      labels:
        run: test-node
    spec:
      containers:
      - name: test-node
        image: "{{ .Values.image.repository }:{{ .Values.image.tag}}"
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 5000
        env:
          - name: PORT
            value: "5000"
        resources:
          limits:
            cpu: 100m # the CPU limit is defined in milicore (m)
            memory: 100Mi # the Memory is defined in Mebibytes (Mi)
        - name: prometheus
        image: hazembenhassine/prom-image
        imagePullPolicy: Always
        ports:
          - name: prometheus
            containerPort: 9090
        resources:
          limits:
            cpu: 100m # the CPU limit is defined in milicore (m)
            memory: 100Mi # the Memory is defined in Mebibytes (Mi)