apiVersion: v1
kind: Service
metadata:
  labels:
    run: test-node
  name: test-node
spec:
  ports:
    - name: prod
      port: 80
      protocol: TCP
      targetPort: web
    - name: prometheus
      port: 9090
      protocol: TCP
      targetPort: prometheus
  selector:
    run: test-node